# @package _global_

defaults:
  - nbprint: nbprint/default
  # NOTE: omit context as it will conflict with ccflow with different meaning,
  # and notebook has no default context. Restore after renaming
  # - context: nbprint/default

  - nbprint/content/frontmatter: []
  - nbprint/content/backmatter: []

  - nbprint/outputs: nbprint/default
  - nbprint/page: nbprint/default
  - nbprint/parameters: nbprint/papermill
  - override hydra/hydra_logging: default
  - override hydra/job_logging: default
  - _self_

callable: /nbprint
